doctrine:
  dbal:
    # configure these for your database server
    url: '%env(resolve:DATABASE_URL)%'
#    driver: 'pdo_pgsql'
#    dbname: candy_wrappers
#    host: 127.0.0.1
#    port: 5432
#    user: '%env(resolve:DATABASE_USER)%'
#    password: '%env(resolve:DATABASE_PASS)%'
#    server_version: '10.10'
#    charset: utf8
#    default_table_options:
#      charset: utf8
#      collate: utf8
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
